[kakaotv_ttunttun]
title = "kakaoTV ─ 개미는 오늘도 뚠뚠"
url = "https://tv.kakao.com/channel/3647847/video"
entrySelector = "ul.list_vertical li"
titleSelector = "strong.tit_item"
linkSelector = "a.link_contents"
contentSelector = "span.mark_play"
imageSelector = "span.thumb_box img.thumb_img"
waitUntil = "networkidle"
onFail = "stale"

[kakaotv_ttunttun2]
title = "kakaoTV ─ 개미는 오늘도 뚠뚠 챕터2"
url = "https://tv.kakao.com/channel/3717609/video"
entrySelector = "ul.list_vertical li"
titleSelector = "strong.tit_item"
linkSelector = "a.link_contents"
contentSelector = "span.mark_play"
imageSelector = "span.thumb_box img.thumb_img"
waitUntil = "networkidle"
onFail = "stale"

[kakaotv_ttunttun3]
title = "kakaoTV ─ 개미는 오늘도 뚠뚠 챕터3"
url = "https://tv.kakao.com/channel/3765289/video"
entrySelector = "ul.list_vertical li"
titleSelector = "strong.tit_item"
linkSelector = "a.link_contents"
contentSelector = "span.mark_play"
imageSelector = "span.thumb_box img.thumb_img"
waitUntil = "networkidle"
onFail = "stale"

[kakaotv_ttunttun4]
title = "kakaoTV ─ 개미는 오늘도 뚠뚠 챕터4"
url = "https://tv.kakao.com/channel/3815196/video"
entrySelector = "ul.list_vertical li"
titleSelector = "strong.tit_item"
linkSelector = "a.link_contents"
contentSelector = "span.mark_play"
imageSelector = "span.thumb_box img.thumb_img"
waitUntil = "networkidle"
onFail = "stale"

[kakaotv_ttunttun5]
title = "kakaoTV ─ 개미는 오늘도 뚠뚠 챕터5"
url = "https://tv.kakao.com/channel/3875615/video"
entrySelector = "ul.list_vertical li"
titleSelector = "strong.tit_item"
linkSelector = "a.link_contents"
contentSelector = "span.mark_play"
imageSelector = "span.thumb_box img.thumb_img"
waitUntil = "networkidle"
onFail = "stale"

[hyunddaily]
title = "디지털데일리 박현영 기자 ─ 네이버 뉴스"
url = "https://media.naver.com/journalist/138/74334"
entrySelector = "ul.press_edit_news_list li.press_edit_news_item.as_thumb"
titleSelector = "span.press_edit_news_title"
linkSelector = "a.press_edit_news_link"
contentSelector = "span.r_ico_b.r_modify"
imageSelector = "span.press_edit_news_thumb img"
waitUntil = "networkidle"

[snek]
title = "스넥"
url = "https://www.snek.ai/alpha/all"
entrySelector = "article.ai-article-item"
titleSelector = "div.ai-article-title h3 a"
linkSelector = "div.ai-article-title h3 a"
contentSelector = "div.ai-article-desc a.a-link-style-none.s-font-caption-small"
imageSelector = "div.ai-article-img-wrap a img"
waitUntil = "networkidle"
