[kakaotv_ttunttun5]
title = "kakaoTV ─ 개미는 오늘도 뚠뚠 챕터5"
url = "https://tv.kakao.com/channel/3875615/video"
entrySelector = "ul.list_vertical li"
titleSelector = "strong.tit_item"
linkSelector = "a.link_contents"
contentSelector = "span.mark_play"
imageSelector = "span.thumb_box img.thumb_img"
waitUntil = "networkidle"